### PR TITLE
Updated to .NET Standard 2.0 and added ability to set Response Type

### PR DESCRIPTION
**Pull request by ajtatum**
Currently, when using SlackBotMessages for SlashCommands when a message is set it defaults to "ephemeral" which means only the user sees the response. I wish to add the ability to set the response type per message. So when someone asks for something the entire channel should see, I can specify "in-channel" but if they ask for /help I can return "ephemeral". 

I hope you don't mind I added myself as an author. If it's a big deal, no worries. Additionally, I don't know your build process... if you use the nuspec or the nupkg from the build, so feel free to edit those as necessary.

Thanks,
AJ

### CODE REVIEW

**Comment by ajtatum** [comment]
I edited the solution using VS 2019 community, which may explain the appveyor error.

**Comment by ajtatum** [comment]
I got it working on my AppVeyor by telling it to ignore your appveyor.yml. My generated yml looks something like this if you want to have a yml file:

version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  EnableNuGetPackageRestore: true
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
.......

**Comment by prjseal** [comment]
Thanks for this, it would be better if you just submitted the small change to the response type rather than the other changes as well. I haven't had chance to test it out yet, but have you made it default to ephemeral?

**Comment by ajtatum** [comment]
Sorry about that, let me try and rework it keeping it with the same version of .net standard.

**Pull request closed without merging**
